apiVersion: v1 
kind: Service 
metadata: 
  name: python-app-service
  namespace: default 
spec: 
  ports: 
  - nodePort: 30814 
    port: 5000 
    protocol: TCP 
    targetPort: 5000 
  selector: 
    app: python-app 
  type: NodePort 
status: 
  loadBalancer: {} 

